export const productos = [
  { id: 1, nombre: "Laptop Pro", precio: 1200, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" },
  { id: 2, nombre: "Smartphone X", precio: 900, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" },
  { id: 3, nombre: "Auriculares Inalámbricos", precio: 150, categoria: "Accesorios", imagen: "https://picsum.photos/150/150" },
  { id: 4, nombre: "Monitor UltraWide", precio: 350, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" },
  { id: 5, nombre: "Teclado Mecánico", precio: 120, categoria: "Accesorios", imagen: "https://picsum.photos/150/150" },
  { id: 6, nombre: "Mouse Gamer", precio: 80, categoria: "Accesorios", imagen: "https://picsum.photos/150/150" },
  { id: 7, nombre: "Silla Ergonómica", precio: 250, categoria: "Muebles", imagen: "https://picsum.photos/150/150" },
  { id: 8, nombre: "Tablet Pro", precio: 700, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" },
  { id: 9, nombre: "Smartwatch Sport", precio: 180, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" },
  { id: 10, nombre: "Cámara Digital", precio: 550, categoria: "Fotografía", imagen: "https://picsum.photos/150/150" },
  { id: 11, nombre: "Lente 50mm", precio: 320, categoria: "Fotografía", imagen: "https://picsum.photos/150/150" },
  { id: 12, nombre: "Micrófono Studio", precio: 200, categoria: "Audio", imagen: "https://picsum.photos/150/150" },
  { id: 13, nombre: "Bocinas Bluetooth", precio: 110, categoria: "Audio", imagen: "https://picsum.photos/150/150" },
  { id: 14, nombre: "Cargador Rápido", precio: 40, categoria: "Accesorios", imagen: "https://picsum.photos/150/150" },
  { id: 15, nombre: "Disco Duro Externo", precio: 130, categoria: "Almacenamiento", imagen: "https://picsum.photos/150/150" },
  { id: 16, nombre: "Memoria USB 128GB", precio: 35, categoria: "Almacenamiento", imagen: "https://picsum.photos/150/150" },
  { id: 17, nombre: "Router WiFi 6", precio: 180, categoria: "Redes", imagen: "https://picsum.photos/150/150" },
  { id: 18, nombre: "Impresora Multifunción", precio: 220, categoria: "Oficina", imagen: "https://picsum.photos/150/150" },
  { id: 19, nombre: "Proyector HD", precio: 400, categoria: "Hogar", imagen: "https://picsum.photos/150/150" },
  { id: 20, nombre: "Refrigerador Smart", precio: 950, categoria: "Electrodomésticos", imagen: "https://picsum.photos/150/150" },
  { id: 21, nombre: "Lavadora Automática", precio: 800, categoria: "Electrodomésticos", imagen: "https://picsum.photos/150/150" },
  { id: 22, nombre: "Cafetera Premium", precio: 180, categoria: "Hogar", imagen: "https://picsum.photos/150/150" },
  { id: 23, nombre: "Televisor 4K 55\"", precio: 750, categoria: "Entretenimiento", imagen: "https://picsum.photos/150/150" },
  { id: 24, nombre: "Consola de Videojuegos", precio: 600, categoria: "Entretenimiento", imagen: "https://picsum.photos/150/150" },
  { id: 25, nombre: "Drone 4K", precio: 1000, categoria: "Tecnología", imagen: "https://picsum.photos/150/150" }
];